# Hardcoded question data with specified criteria
# Hardcoded question data with specified criteria including scores
question_data = [
  {"question_no": 1, "question_text": "At a party do you:", "options": ["A. Interact with many, including strangers", "B. Interact with a few, known to you"], "score": ["E", "I"]},
  {"question_no": 2, "question_text": "In your social groups do you:", "options": ["A. Keep abreast of other’s happenings", "B. Get behind on the news"], "score": ["E", "I"]},
  {"question_no": 3, "question_text": "In phoning do you:", "options": ["A. Rarely question that it will all be said", "B. Rehearse what you’ll say"], "score": ["E", "I"]},
  {"question_no": 4, "question_text": "In company do you:", "options": ["A. Initiate conversation", "B. Wait to be approached"], "score": ["E", "I"]},
  {"question_no": 5, "question_text": "Does new and non-routine interaction with others:", "options": ["A. Stimulate and energize you", "B. Tax your reserves"], "score": ["E", "I"]},
  {"question_no": 6, "question_text": "Do you prefer:", "options": ["A. Many friends with brief contact", "B. A few friends with more lengthy contact"], "score": ["E", "I"]},
  {"question_no": 7, "question_text": "Do you:", "options": ["A. Speak easily and at length with strangers", "B. Find little to say to strangers"], "score": ["E", "I"]},
  {"question_no": 8, "question_text": "When the phone rings do you:", "options": ["A. Hasten to get to it first", "B. Hope someone else will answer"], "score": ["E", "I"]},
  {"question_no": 9, "question_text": "Are you more inclined to be:", "options": ["A. Easy to approach", "B. Somewhat reserved"], "score": ["E", "I"]},
  {"question_no": 10, "question_text": "Are you more:", "options": ["A. Realistic than speculative", "B. Speculative than realistic"], "score": ["S", "N"]},
  {"question_no": 11, "question_text": "Is it worse to:", "options": ["A. Have your 'head in the clouds'", "B. Be 'in a rut'"], "score": ["S", "N"]},
  {"question_no": 12, "question_text": "Are you more attracted to:", "options": ["A. Sensible people", "B. Imaginative people"], "score": ["S", "N"]},
  {"question_no": 13, "question_text": "Are you more interested in:", "options": ["A. What is actual", "B. What is possible"], "score": ["S", "N"]},
  {"question_no": 14, "question_text": "In doing ordinary things are you more likely to:", "options": ["A. Do it the usual way", "B. Do it your own way"], "score": ["S", "N"]},
  {"question_no": 15, "question_text": "Facts:", "options": ["A. 'Speak for themselves'", "B. Illustrate principles"], "score": ["S", "N"]},
  {"question_no": 16, "question_text": "Are visionaries:", "options": ["A. Somewhat annoying", "B. Rather fascinating"], "score": ["S", "N"]},
  {"question_no": 17, "question_text": "Common sense is:", "options": ["A. Rarely questionable", "B. Frequently questionable"], "score": ["S", "N"]},
  {"question_no": 18, "question_text": "Children often do not:", "options": ["A. Make themselves useful enough", "B. Exercise their fantasy enough"], "score": ["S", "N"]},
  {"question_no": 19, "question_text": "Are you more impressed by:", "options": ["A. Principles", "B. Emotions"], "score": ["T", "F"]},
  {"question_no": 20, "question_text": "Are more drawn toward the:", "options": ["A. Convincing", "B. Touching"], "score": ["T", "F"]},
  {"question_no": 21, "question_text": "In judging others are you more swayed by:", "options": ["A. Laws than circumstances", "B. Circumstances than laws"], "score": ["T", "F"]},
  {"question_no": 22, "question_text": "In approaching others is your inclination to be somewhat:", "options": ["A. Objective", "B. Personal"], "score": ["T", "F"]},
  {"question_no": 23, "question_text": "Which appeals to you more:", "options": ["A. Consistency of thought", "B. Harmonious human relationships"], "score": ["T", "F"]},
  {"question_no": 24, "question_text": "Are you more comfortable in making:", "options": ["A. Logical judgments", "B. Value judgments"], "score": ["T", "F"]},
  {"question_no": 25, "question_text": "Are you more often:", "options": ["A. A cool-headed person", "B. A warm-hearted person"], "score": ["T", "F"]},
  {"question_no": 26, "question_text": "Is it worse to be:", "options": ["A. Unjust", "B. Merciless"], "score": ["T", "F"]},
  {"question_no": 27, "question_text": "In making decisions do you feel more comfortable with:", "options": ["A. Standards", "B. Feelings"], "score": ["T", "F"]},
  {"question_no": 28, "question_text": "Do you prefer to work:", "options": ["A. To deadlines", "B. Just 'whenever'"], "score": ["J", "P"]},
  {"question_no": 29, "question_text": "Do you tend to choose:", "options": ["A. Rather carefully", "B. Somewhat impulsively"], "score": ["J", "P"]},
  {"question_no": 30, "question_text": "Are you more:", "options": ["A. Punctual", "B. Leisurely"], "score": ["J", "P"]},
  {"question_no": 31, "question_text": "Does it bother you more having things:", "options": ["A. Incomplete", "B. Completed"], "score": ["J", "P"]},
  {"question_no": 32, "question_text": "Do you want things:", "options": ["A. Settled and decided", "B. Unsettled and undecided"], "score": ["J", "P"]},
  {"question_no": 33, "question_text": "Would you say you are more:", "options": ["A. Serious and determined", "B. Easy-going"], "score": ["J", "P"]},
  {"question_no": 34, "question_text": "Should one usually let events occur:", "options": ["A. By careful selection and choice", "B. Randomly and by chance"], "score": ["J", "P"]},
  {"question_no": 35, "question_text": "Do you feel better about:", "options": ["A. Having purchased", "B. Having the option to buy"], "score": ["J", "P"]},
  {"question_no": 36, "question_text": "Which is more admirable:", "options": ["A. The ability to organize and be methodical", "B. The ability to adapt and make do"], "score": ["J", "P"]}
]
